version: '2.3'

services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/papanage/wikitabia-telegram-bot
      RUNNER_NAME: wikitabia-runner
      RUNNER_TOKEN: AP5IDQJWJ7ZF7D5ITKDPG7TCS425W
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
