name: Build and Delivery dev

on:
  pull_request:
  push:

jobs:
  delivery:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Maven Verify
        run: mvn clean install
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.DOCKER_REGISTRY_URL}}
          username: ${{secrets.DOCKER_REGISTRY_LOGIN}}
          password: ${{secrets.DOCKER_REGISTRY_PASS}}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{secrets.DOCKER_REGISTRY_URL}}/${{secrets.DOCKER_REGISTRY_REPO}}/${{secrets.DOCKER_REGISTRY_IMAGE}}:${{secrets.DOCKER_REGISTRY_IMAGE_TAG_DEV}}
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_HOST_USER}}
          password: ${{secrets.DEV_HOST_PASSWORD}}
          port: 22
          source: "docker-compose.yaml"
          target: "wikibot/deployment"
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{secrets.DEV_HOST}}
          user: ${{secrets.DEV_HOST_USER}}
          pass: ${{secrets.DEV_HOST_PASSWORD}}
          run: |
            docker rmi ${{secrets.DOCKER_REGISTRY_URL}}/${{secrets.DOCKER_REGISTRY_REPO}}/${{secrets.DOCKER_REGISTRY_IMAGE}}:${{secrets.DOCKER_REGISTRY_IMAGE_TAG_DEV}}
            echo WIKITABIA_BOT_OUTER_PORT=${{secrets.WIKITABIA_BOT_OUTER_PORT}} > wikibot/deployment/.env
            echo REGISTRY_URL=${{secrets.DOCKER_REGISTRY_URL}} >> wikibot/deployment/.env
            echo WIKITABIA_BOT_REPO=${{secrets.DOCKER_REGISTRY_REPO}} >> wikibot/deployment/.env
            echo WIKITABIA_BOT_IMAGE_NAME=${{secrets.DOCKER_REGISTRY_IMAGE}} >> wikibot/deployment/.env
            echo WIKITABIA_BOT_IMAGE_TAG=${{secrets.DOCKER_REGISTRY_IMAGE_TAG_DEV}} >> wikibot/deployment/.env
            echo APPLICATION_TOKEN=${{secrets.APPLICATION_TOKEN}} >> wikibot/deployment/.env
            cd wikibot/deployment && docker compose up -d
            
